name: Sync DB to Neon

on:
  push:
    branches:
      - preview

jobs:
  sync-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Export local database
        run: |
          pg_dump -U ${{ secrets.DB_LOCAL_USER }} -h ${{ secrets.DB_LOCAL_HOST }} -p 5432 -Fc -d ${{ secrets.DB_LOCAL_NAME }} > dump_local.pgsql

      - name: Import to Neon
        run: |
          pg_restore --verbose --clean --no-owner --no-acl -U ${{ secrets.DB_NEON_USER }} -h ${{ secrets.DB_NEON_HOST }} -p 5432 -d ${{ secrets.DB_NEON_NAME }} < dump_local.pgsql